name: Node.js Package

on:
  release:
    types: [created]  # Run workflow when create release 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  
      - uses: actions/setup-node@v4  
        with:
          node-version: 20  
      - run: npm ci 
      - run: npm test  

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Role
    steps:
      - uses: actions/checkout@v4  
      - uses: actions/setup-node@v4 
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/  # GitHub Packages is registry
      - run: npm ci  # Install dependencies
      - run: npm publish  # Publish package on GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}  # GitHub Token automatic
